### ISSUE TITLE
Copy To Clipboard

### ISSUE THREAD

**Issue by kisp** [cgfrost/moolater#1]
Just got an idea about a new feature for moolater, which I very much enjoy.

I wish I had a "Copy To Clipboard" button (or small iconic button), that would allow
me to copy the Task and Link fields to the clipboard _together_.

For the current page I am on, this would allow me to paste

```
New Issue · cgfrost/moolater
https://github.com/cgfrost/moolater/issues/new
```

here in one go.

I regularly trap myself wanting to take a note of a page I am on and saving this as a
task in RTM, although it would be better kept somewhere else.

**Comment by cgfrost** [comment]
I'm re-writing MooLater for the newer versions of Firfox at the moment, I'll add this in. Simple to do.

**Comment by kisp** [comment]
That would be great! :-) Thanks!

**Comment by cgfrost** [comment]
The Firefox extensions API only supports copy images to the clipboard. An update to support text as well is meant to be coming soon. I will keep an eye on it and implement it when possible.

FYI https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/clipboard

**Comment by cgfrost** [comment]
Two years later and according to the docs this might now be possible but would require some investigation as the docs are not consistent. The following implies it can be done.

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

**Comment by cgfrost** [comment]
@kisp Would you expect to see this as a separate function or a by-product of saving the task to RTM. Having played around with the implementation, it's beyond the scope of this extension to save things to the clipboard that have nothing to do with RTM.

**Comment by kisp** [comment]
@cgfrost  Hi, maybe this feature is off-topic then for moolater. There are other Add-ons like "Copy Tab Urls" that can do the job. My intended behaviour for moolater would be to have the copy to clipboard as a separate function.

Shall we close this issue then?

Sorry about my late reply

**Comment by cgfrost** [comment]
Hi, thank you for understanding. Closing as off-topic.
