### ISSUE TITLE
Add a date picker for new tasks.

### ISSUE THREAD

**Issue by cgfrost** [cgfrost/moolater#10]
https://addons.mozilla.org/en-US/firefox/addon/moo-later/reviews/1128094/

**Comment by liowalter** [comment]
That would be great ! But thanks a lot for this extension !

**Comment by cgfrost** [comment]
Will add a date picker and enhance the UI to show when the smart add feature is enabled.

**Comment by liowalter** [comment]
great, thanks !

**Comment by cgfrost** [comment]
New feature has been added, will be released soon.

**Comment by cgfrost** [comment]
Released in version 3.0
