### ISSUE TITLE
Dark theme ^^

### ISSUE THREAD

**Issue by alkaphreak** [cgfrost/moolater#11]
Hi, i'm using a dark theme for my ubuntu and firefox env, as you can see in the capture, there is problem with the text display of the Moolater popup. The text is grey and often hardly visible.

Can you provide an option for a dark theme or simply force field form background and text color to give more readability. 

Thanks a lot.

![moolater-dark-theme-capture](https://user-images.githubusercontent.com/4222406/50826080-09355880-133b-11e9-8b91-5ea93a8db384.png)

**Comment by cgfrost** [comment]
Resolved in https://github.com/cgfrost/moolater/pull/12
