### ISSUE TITLE
Error : 300 Timeline invalid or not provided

### ISSUE THREAD

**Issue by alkaphreak** [cgfrost/moolater#2]
When i use the plugin, sometimes (often), i got this error :
> Error : 300 Timeline invalid or not provided

---
Ubuntu 16.04.2 LTS x86_64
Firefox 53.0
MOO Later 1.2.0

**Comment by cgfrost** [comment]
Thanks for raising the bug, I'm re-writing MooLater for the new version of Firefox, will try and fix this at the same time.

**Comment by alkaphreak** [comment]
Nice ;)

**Comment by cgfrost** [comment]
The new version is ready to go, just doing some final testing. I have been unable to recreate this error but to be on the safe side I have added code to re-create the timeline if it becomes invalid and automatically retry the failed request to Remember the milk. I will close this issue once I've published the new release, later today. Thanks for using my Add-on, I hope you continue to like it.

**Comment by cgfrost** [comment]
Version 2.0 is now available, please let me know if you find any bugs.

Happy new year.

**Comment by alkaphreak** [comment]
Will take a look tomorrow. Thanks a lot.

Le 2 janv. 2018 00:45, "Christopher Frost" <notifications@github.com> a
écrit :
