### ISSUE TITLE
Url not included

### ISSUE THREAD

**Issue by alkaphreak** [cgfrost/moolater#7]
Hi, i'm using your latest release of Moolater (1.2.0) on Firefox ESR 52.5.2 (64-bit) (linux debian 9) and when i click on the magic button, then "Add Task", i see success the message "[object][object]" and when i'm going in RTM to see my, task there is no url attached.

**Comment by cgfrost** [comment]
So I have to make several calls to Remember the milk, first the create the new task and then another one to add the URL. It would appear the one to add the URL is failing and the [object][object] is the error message not displaying properly. 

Can you confirm the task is being added to the Remember the milk ok?
Does this happen with every webpage you try to save or is it just one website in particular, if it's just the one, could you share the URL for it. I understand if you don't want to. I might need to add some character escaping etc... for it.

As a side note, if you are able to upgrade to a newer version of Firefox you can get MooLater 2.x which is a big re-write and includes lots of bug fixes. If you need to stick with ERS releases the next one is out

**Comment by alkaphreak** [comment]
Hi. I can confirm : 
- that the task is being added to the list
- the task is added without the link/url
- this happen on every page for this configuration (FF ESR, Debian 9, ...)
- this isn't happening for others conf (Ubuntu/Windows, FF 57+ ...)

I made this issue to improve the MooLater ext. I should be able to update my FF, this version is the one provided by debian.
